### PR TITLE
remove registry argument

### PR DESCRIPTION
**Pull request by pqt**
Just figured out this can be done from a hidden environment variable and in `.npmrc`

### CODE REVIEW

**Comment by tjanson** [comment]
heads up: you _always_ need to populate the NPM auth token env var when running _any_ `npm` command (whether it uses the auth or not), just because the config (which is always read) isn’t parsed as valid otherwise

yeah

**Comment by pqt** [comment]
🤦🏼‍♂️

Interesting @tjanson Hopefully I get this wrapped up and figured out before Christmas.

**Comment by tjanson** [comment]
Trust me, I’ve spent a similar amount on this. Let’s just say it’s still rough around the edges. I’ve had just as much fun with the GPR Maven registry too (which I still haven’t gotten to work fully).

**Comment by pqt** [comment]
I'll probably fall in love with this once it's all hooked up and seamless. I knew what I was getting into with the beta. I just wish the errors were a little more explicit or unfiltered. We're all developers here, after all.

**Pull request merged**
